Finished arrays
solar05/study pull request #1
Opened 2020-05-10 22:46 UTC by solar05

2020-05-14 12:40 UTC, Andrew8xx8 commented
Тесты падают

2020-05-14 12:41 UTC, Andrew8xx8 requested changes

2020-05-14 12:41 UTC, Andrew8xx8 commented on test/exercise/arrays/solution.rb
> +        max = array.max
Внимательно прочти задание, max нельзя использовать

2020-05-14 12:41 UTC, Andrew8xx8 commented on test/exercise/arrays/solution.rb
> +        def binary(array, left_border, right_border, element)
Не нужно метод внутри метода определять. Перенеси на уровень класса например

2020-05-14 19:48 UTC, solar05 commented
 Хм, странно, локально рубокоп 
![image](https://user-images.githubusercontent.com/38437931/81978413-24e9f680-9634-11ea-9911-3ee7c8626aac.png)
и тесты 
![image](https://user-images.githubusercontent.com/38437931/81978463-3a5f2080-9634-11ea-8b07-61714e888e90.png)
работают как надо, а тревис все равно падает

2020-05-14 20:52 UTC, artempartos commented
надо править в рубокопе, чтобы в тревисе прошло
```
Error: The `Style/TrailingCommaInLiteral` cop has been removed. Please use `Style/TrailingCommaInArrayLiteral` and/or `Style/TrailingCommaInHashLiteral` instead.
```
https://travis-ci.com/github/solar05/study

2020-05-27 10:56 UTC, artempartos commented
поправь чтобы рубокоп проверял только файлы внутри директории с приложением

2020-05-27 10:58 UTC, artempartos requested changes

2020-05-27 10:58 UTC, artempartos commented on test/exercise/arrays/solution.rb
> +          return array.index(element).nil? ? -1 : array.index(element)
мне не нравится использование array.index здесь, есть вариант гораздо проще

2020-05-27 10:58 UTC, artempartos commented on test/exercise/arrays/solution.rb
> +          return array.index(element).nil? ? -1 : array.index(element)
в остальном ок

2020-06-09 20:24 UTC, Andrew8xx8 approved these changes

2020-06-12 16:06 UTC, merged